### ISSUE TITLE
Get Font Provider for Prettier Fonts in Pure Edition

### ISSUE THREAD

**Issue by oxr463** [theblackwidower/KanaQuiz#11]
It is more than likely that a user running the pure apk will not use Play Store to download this optional application. Is there another font provider that can be used instead?

**Comment by theblackwidower** [comment]
Thought I did. If it doesn't detect the Play Store on the device, it gives you a link to the GitHub, I think... yes, it should provide a link to the GitHub page. If it's not, that is an actual issue.

I guess I could get it to detect F-Droid, but that application is not available there.

Unless you're suggesting I use a different Font Provider app. Well, I don't think I can, because I don't know of any others that exist. And to be honest, it's a low priority.

My suggestion: Upgrade to Android Pie, which has the fonts built in, and therefore doesn't need Font Provider, or just use a non-serifed theme, which would be either "Shibuya Night" or "Hot Spring Serenity".
