### ISSUE TITLE
[Feature request] Add Dark Theme

### ISSUE THREAD

**Issue by ditokp** [theblackwidower/KanaQuiz#8]
Add dark theme, please

**Comment by theblackwidower** [comment]
Hmmm... that's actually not a bad idea. But I have a genuine question, because I've seen a lot of my former colleagues use dark themes and at least a few developer utilities I've run across use dark themes by default, and I genuinely haven't understood the appeal of those since I left my goth phase. Is there something I'm missing?

But I'll definitely look into this. I've been thinking of adding selectable fonts as well. So if I'm going to do this, I'm going all out. Might consider a complete visual redesign.

**Comment by ditokp** [comment]
Wow, thank you very much for making this app great.

I like dark theme because its not hurting my eyes :-)

**Comment by theblackwidower** [comment]
Yeah, funnily enough, after asking that question, I found a whole article on this.

https://www.androidcentral.com/dark-themes-norm-not-exception

I'm just used to doing most of my work in bright environments, because dark environments exacerbate my depression. But if you're in a dark environment (ie: in bed trying to sleep but can't be asked so you grab your phone), a dark theme prevents your eyes from suddenly freaking out.

So yeah, makes a lot of sense. Don't know where to start though. This is going to be an interesting one.

**Comment by ditokp** [comment]
Okay, now I want to make other dark theme request on other Foss app :-)

**Comment by ditokp** [comment]
Can I ask you something? Where do you from? Because your replying my message very fast

**Comment by theblackwidower** [comment]
If they wonder why, link to that article.
